sudo: required
language: node_js
os:
  - linux
node_js:
  - "12"
services:
  - xvfb
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
before_script:
  - >-
    LATEST_CHROMEDRIVER_VERSION=`curl -s
    "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - >-
    curl
    "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
    -O
  - unzip chromedriver_linux64.zip -d ~/bin
before_install:
  - node --version
  - npm --version
  - export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  - pip install --user codecov
after_success:
  - codecov
script:
  # Run code styling
  - npm run lint
  # Run tests
  - npm run test:unit
  - npm run test:e2e-ci
