sudo: required
language: node_js
os:
  - linux
node_js:
  - "8"
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  - node --version
  - npm --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install --user codecov
after_success:
  - codecov
script:
  # Run code styling
  - npm run lint
  # Run tests
  - npm run test:unit
  - npm run test:e2e-ci
