name: CI Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare node-gyp for ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install g++ build-essential

      - name: npm install, build, and test
        run: |
          npm i
          npm run lint
          npm test:unit
        env:
          CI: true
