name: CI Build

on:
  push:
    branches:
      - master
      - feature/**

concurrency:
  group: cibuild-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare node-gyp for ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install g++ build-essential

      - name: npm install, build, and test
        run: |
          npm i
          npm run lint
          npm run test:unit
          npm run test:e2e-ci
        env:
          CI: true
